#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "migrate"
python manage.py migrate
echo "run server"
gunicorn --worker-class=gevent --worker-connections=1000 --workers=3 Grrid.wsgi:application --bind 0.0.0.0:8000
